# Generated by Django 2.2.2 on 2019-07-02 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190702_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='library_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Library_name'),
            preserve_default=False,
        ),
    ]
